apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
data:
  DJANGO_DEBUG: {{ .Values.config.debug | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  DB_NAME: {{ .Values.config.database.name | quote }}
  CELERY_BROKER_URL: {{ .Values.config.celery.brokerUrl | quote }}
  CELERY_RESULT_BACKEND: {{ .Values.config.celery.resultBackend | quote }}
  REDIS_URL: {{ .Values.config.redis.url | quote }}
