apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | b64enc | quote }}
  DB_USER: {{ .Values.secrets.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.database.password | b64enc | quote }}
